### ISSUE TITLE
First move can be played outside the starting 4 squares

### ISSUE THREAD

**Issue by MilesWT** [bdavs/TournamentAdjudicator#11]

**Comment by keithalbe** [comment]
I believe this has been resolved Miles, but just to be sure, could you provide a little more information? Did this occur on the first move, or had player 1 made an invalid move, and another player was allowed to play outside the starting 4 squares?

**Comment by MilesWT** [comment]
This occurred on the first move of the game by player 1. I tested this again, and indeed it has been resolved. Thanks Keith.
