### ISSUE TITLE
AI is receiving tiles it should not be able to receive

### ISSUE THREAD

**Issue by cparks1** [bdavs/TournamentAdjudicator#12]
![image](https://cloud.githubusercontent.com/assets/18123277/20821494/f0682dc8-b810-11e6-81f1-ef3e1faa62a0.png)

The AI client on the top has received 2 Qu tiles, and this is simply not possible. I have a feeling it may be that the tile bag is not being updated when tiles are handed out to the AI.

**Comment by bdavs** [comment]
My assumption is that it's an error with the givetiles function only removing the first letter. @ghaddad can you look into it.

**Comment by DanGarcia595** [comment]
Agreed.

**Comment by bdavs** [comment]
Was not removing proper tile from bag. Should be resolved. Please confirm

**Comment by bdavs** [comment]
Confirmed
