### ISSUE TITLE
Valid 7-letter first move rejected

### ISSUE THREAD

**Issue by MilesWT** [bdavs/TournamentAdjudicator#13]
Player 1 tried to play ALIENER, a valid word in the dictionary, which covers the starting tiles (x=4,y=4) and (x=5, y=4), a valid move. It starts on a tile that is not one of the starting tiles, but the rules only stipulate the word must cover those tiles not start on them. Maybe something to do with it also reaching the edge of the board?
But the adjudicator rejected it as invalid:
![image](https://cloud.githubusercontent.com/assets/11743094/21078639/acc3d6e0-bf44-11e6-93b9-209de64c7558.png)
From the rule book:
![image](https://cloud.githubusercontent.com/assets/11743094/21078625/cdae9972-bf43-11e6-908d-36d05a2b60bd.png)

Yet after this first move was rejected, the subsequent move by Player 2 was accepted, and it also started not on the starting tiles but still covered them:
![image](https://cloud.githubusercontent.com/assets/11743094/21078636/4b3cce4a-bf44-11e6-8b9e-e1c30828b049.png)

**Comment by MilesWT** [comment]
Here are the contents of the associated log file:
----------------------------------------------------
%%%%% ERROR INVALID MOVE!!! %%%%%
Error Message: 
Some of the changed game squares were invalid.

TeamNum: 1
Timestamp: 12/11/2016 1:35:35 AM
Team Score: 0
Playable Letters: 
R L N A I E E 
Word(s) Played: 
ALIENER

**********************************

VALID MOVE!

TeamNum: 2
Timestamp: 12/11/2016 1:35:35 AM
Team Score: 12
Playable Letters: 
N D M S S E E 
Word(s) Played: 
MESSED

**********************************

PASS

TeamNum: 1
Timestamp: 12/11/2016 1:35:35 AM
Team Score: 0
Playable Letters: 
R L N A I E E 

**********************************

PASS

TeamNum: 2
Timestamp: 12/11/2016 1:35:35 AM
Team Score: 12
Playable Letters: 
N I I T S O U 

**********************************

**Comment by bdavs** [comment]
@MilesWT Can you confirm this solved the issue

**Comment by MilesWT** [comment]
I verified it fixed the issue too.
