### ISSUE TITLE
Trouble playing large move?

### ISSUE THREAD

**Issue by MilesWT** [bdavs/TournamentAdjudicator#14]
Player 1 makes valid move:
![image](https://cloud.githubusercontent.com/assets/11743094/21086252/c2edffd2-bfe8-11e6-9ded-7ff7c7fc1ff5.png)

Than Player 2 makes valid move but it is rejected because it is "out of bounds" but it is not.
It plays LIABILITY by playing LIABI
![image](https://cloud.githubusercontent.com/assets/11743094/21086286/20e8d774-bfe9-11e6-97a4-809fc7c57f07.png)

ALSO, player 2 continues to try to play this word again because it gets the same tiles back and the same board state, and it is still player 2's turn.

Log File:
---------

VALID MOVE!

TeamNum: 1
Timestamp: 12/11/2016 9:25:47 PM
Team Score: 12
Playable Letters: 
T I A L Y P O 
Word(s) Played: 
POLITY

**********************************

**Comment by keithalbe** [comment]
I also recreated this issue, I did not get an invalid move. I recommend the same course of action that i included in the comment for issue #15 

Here is the log showing my results when recreating the same issue:

VALID MOVE!

TeamNum: 1
Timestamp: 12/11/2016 11:31:42 PM
Team Score: 12
Playable Letters: 
T I A L Y P O 
Word(s) Played: 
POLITY

**********************************

VALID MOVE!

TeamNum: 2
Timestamp: 12/11/2016 11:32:24 PM
Team Score: 11
Playable Letters: 
L I A B I I L 
Word(s) Played: 
LIABILITY

**********************************

**Comment by MilesWT** [comment]
Yeah we realized this was our issue, sorry about that.
