### ISSUE TITLE
False: Letter(s) played were not from the player's letter pool.

### ISSUE THREAD

**Issue by MilesWT** [bdavs/TournamentAdjudicator#15]
The issue may lie with letters being playing non-consecutively, although this is not against the rules.
Player 1 plays valid move:
![image](https://cloud.githubusercontent.com/assets/11743094/21086450/b9b7ee76-bfea-11e6-8651-447e3290a6bb.png)

Player 2 plays valid move:
![image](https://cloud.githubusercontent.com/assets/11743094/21086463/cf62e1f4-bfea-11e6-935a-806de039a35f.png)

Player 1 plays, makes valid move, it is rejected:
![image](https://cloud.githubusercontent.com/assets/11743094/21086513/3ea1637e-bfeb-11e6-8a70-a0b9763c7bcb.png)

Player 2 plays, makes valid move, it is rejected:
![image](https://cloud.githubusercontent.com/assets/11743094/21086496/0f8e9962-bfeb-11e6-9bfa-35a150f8e6a9.png)

Log file:
---------

VALID MOVE!

TeamNum: 1
Timestamp: 12/11/2016 9:36:50 PM
Team Score: 8
Playable Letters: 
A R C D R D M 
Word(s) Played: 
DRAD

**********************************

VALID MOVE!

TeamNum: 2
Timestamp: 12/11/2016 9:36:50 PM
Team Score: 11
Playable Letters: 
O T H M U M T 
Word(s) Played: 
MOUTH
TRAD

**********************************

%%%%% ERROR INVALID MOVE!!! %%%%%
Error Message: 
Letter(s) played were not from the player's letter pool.

TeamNum: 1
Timestamp: 12/11/2016 9:36:50 PM
Team Score: 8
Playable Letters: 
C R M P U N L 
Word(s) Played: 
UNCLAMP
MOUCH

**********************************

%%%%% ERROR INVALID MOVE!!! %%%%%
Error Message: 
Letter(s) played were not from the player's letter pool.

TeamNum: 2
Timestamp: 12/11/2016 9:36:50 PM
Team Score: 11
Playable Letters: 
M T H G G S F 
Word(s) Played: 
STRATH
MOUTH

**********************************

**Comment by bdavs** [comment]
I believe that this stems from the same issue as #14. not sure yet though

**Comment by keithalbe** [comment]
**Miles, I recreated your exact scenario and did not obtain the same error. Can you please make sure to acquire the latest GitHub release, and let me know if you run into the issue again? I am not trying to push the blame on you (it may still be our fault), but also you may want to verify that your AI is sending the messages you believe it is (another team had this problem).

As Bobby mentioned, this problem could be tied in with issue 14. I will start taking a look at 14, and let you know if I stumble upon anything that could be related.

Here is the log where I recreated your issue:**

VALID MOVE!

TeamNum: 1
Timestamp: 12/11/2016 10:56:32 PM
Team Score: 8
Playable Letters: 
A R C D R D M 
Word(s) Played: 
DRAD

**********************************

VALID MOVE!

TeamNum: 2
Timestamp: 12/11/2016 10:56:51 PM
Team Score: 11
Playable Letters: 
O T H M U M T 
Word(s) Played: 
MOUTH
TRAD

**********************************

VALID MOVE!

TeamNum: 1
Timestamp: 12/11/2016 10:58:20 PM
Team Score: 26
Playable Letters: 
C R M P U N L 
Word(s) Played: 
UNCLAMP
MOUCH

**********************************

**Comment by MilesWT** [comment]
Yeah we realized this was our issue, sorry about that.
