### ISSUE TITLE
what is wrong in last move ?

### ISSUE THREAD

**Issue by tanmaythakar4** [bdavs/TournamentAdjudicator#16]
1)

![error](https://cloud.githubusercontent.com/assets/8337449/21163816/36bced26-c163-11e6-816b-54e08a5af4de.PNG)

2)

![error1](https://cloud.githubusercontent.com/assets/8337449/21164491/451ddc6e-c167-11e6-9228-98203f265f6d.PNG)

@bdavs 
I think the last two moves are valid .

Log:

VALID MOVE!

Turn: 0
TeamNum: 1
Timestamp: 12/13/2016 6:26:57 PM
Team Score: 12
Playable Letters: 
M K H N I I O 
Word(s) Played: 
MOKIHI

**********************************

%%%%% ERROR INVALID MOVE!!! %%%%%
Error Message: 
Illegally placed tile on board.

Turn: 1
TeamNum: 2
Timestamp: 12/13/2016 6:26:59 PM
Team Score: 0
Playable Letters: 
M Z P R A O A 
Word(s) Played: 
AROMA
MO
OM
KA

**********************************

%%%%% ERROR INVALID MOVE!!! %%%%%
Error Message: 
Illegally placed tile on board.

Turn: 2
TeamNum: 1
Timestamp: 12/13/2016 7:01:23 PM
Team Score: 12
Playable Letters: 
N S H D S F E 
Word(s) Played: 
MOKIHIS
SNEDS

**********************************

**Comment by keithalbe** [comment]
I believe this error has been resolved in commit 151.
