### ISSUE TITLE
Receive 14 rack tiles in 4 player game after first move

### ISSUE THREAD

**Issue by MilesWT** [bdavs/TournamentAdjudicator#3]
When playing a 4 player game, the behavior of the adjudicator is correct for player 1 but for player 2,3 and 4, they all receive twice as many tiles as they should.

Player 2 (P1 played GIT):
![adjudicator git error](https://cloud.githubusercontent.com/assets/11743094/20682321/8c4b0a60-b575-11e6-8aff-85299124fd70.JPG)

Player 3 (P2 played OUT):
![adjudicator git error2](https://cloud.githubusercontent.com/assets/11743094/20682343/9bd8e06a-b575-11e6-8e09-7cae84ed289e.JPG)

**Comment by DanGarcia595** [comment]
Seems like a gameplay issue. Specifically when letters are added.

**Comment by tanmaythakar4** [comment]
+1

**Comment by bdavs** [comment]
Repeated code removed.  Should be resolved
