### ISSUE TITLE
P1 makes invalid move, P2's valid move is invalid for subsequent turns. Also words not in dictionary are being accepted once this bug is triggered. Also too few tiles are being given in rack.

### ISSUE THREAD

**Issue by MilesWT** [bdavs/TournamentAdjudicator#4]
- The primary bug here is P2's moves are all invalid if P1 makes an invalid move, in this case by playing nothing and returning an unchanged board state in an attempt to pass.
- Once this bug is triggered, other things went wrong too, so fixing the first bug could solve the other two subsequent bugs.
- Once this happens, words not in dictionary can be played by P1.
- Once this happens, both players start to receive too few tiles, beginning with P2.

Start two player game.
P1 gets no vowels, cannot play anything.
![image](https://cloud.githubusercontent.com/assets/11743094/20740353/5e0a06da-b690-11e6-8dc8-dc79a5cea52c.png)
P1 tries to pass by not playing anything.
→ Adjudicator returns invalid move. Shouldn’t it just pass? This is a bug.
![image](https://cloud.githubusercontent.com/assets/11743094/20740363/66b1b42c-b690-11e6-8359-0c1c3f7b877a.png)
Now P2 receives board, P2 gets blank board:
![image](https://cloud.githubusercontent.com/assets/11743094/20740369/78b68dfa-b690-11e6-8235-dacc73dcf008.png)
P2 plays GUYS:
→ Invalid move? This is a bug.
![image](https://cloud.githubusercontent.com/assets/11743094/20740383/8e61df42-b690-11e6-905e-d79c38fe20f1.png)
Now P1 gets blank board since all moves have been invalidated thus far:
![image](https://cloud.githubusercontent.com/assets/11743094/20740388/9848f5b8-b690-11e6-97ee-ff8c7bcb73d0.png)
P1 plays Z (not in the dictionary)
→ Move is accepted? This is a bug.
![image](https://cloud.githubusercontent.com/assets/11743094/20740393/a3790db0-b690-11e6-9c89-4eeba2e2c69b.png)
P2 gets board
→ Z has indeed been accepted as a valid word??:
→ also P2 only got 6 tiles instead of 7. (Even though at the start of the game it got 7 tiles, ruling out miscounting of Qu tile initially, except maybe something else makes this go awry).
![image](https://cloud.githubusercontent.com/assets/11743094/20740406/c550980e-b690-11e6-830f-f57ed7c80e04.png)
P2 tries to play FY (which IS a valid word):
→ FY is rejected! (maybe because Z is invalid from before but somehow got through validity checks?)
![image](https://cloud.githubusercontent.com/assets/11743094/20740411/cfc12fa6-b690-11e6-9ba1-2aceb5a8b189.png)
P1 receives board:
![image](https://cloud.githubusercontent.com/assets/11743094/20740420/d8b0b230-b690-11e6-9744-8946297ba563.png)
P1 sends garbage move “EJ” with tiles it doesn’t have, it is returned as an invalid move as it should be:
![image](https://cloud.githubusercontent.com/assets/11743094/20740424/e2029ca4-b690-11e6-9acf-405d033e0b6a.png)
Now P2 receives the board,
→ But only gets 4 tiles?
![image](https://cloud.githubusercontent.com/assets/11743094/20740427/ea59fd66-b690-11e6-8c9d-d078ad871f7f.png)
P2 can’t really play, so it tries to pass by playing nothing, but receives invalid move:
![image](https://cloud.githubusercontent.com/assets/11743094/20740434/f928127e-b690-11e6-8363-cc64749f459f.png)
Now P1 receives board,
→ and it only gets 6 tiles?
![image](https://cloud.githubusercontent.com/assets/11743094/20740438/0352bbe6-b691-11e6-8423-cb87d0ac9616.png)

**Comment by DanGarcia595** [comment]
Keith pushed 3819b6ed58c3261b88bf8f8603d8aaf03059d6e8 and unassigned himself. I'll take that as a close. If you want Keith, you can do this automagically by putting the issue number in the commit eg "Fixed letters issue #4" and it will autoclose the issue.
